Fix improper naming. Fix messy codes. Remove redundant type annotations.
ecstaciEva/todo-list-typescript pull request #4
Opened 2021-05-25 08:53 UTC by ecstaciEva

- Fix improper naming.
- Fix messy codes, using appropriate methods instead.
- Remove redundant type annotations.

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/AddTodoForm.tsx
> +        style={{ border: 0, marginBottom: 10 }}
Do not use style.
Use className

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    const timestamp: number = Date.now();
`: number` is redundant.
Type can be inferred.

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos(todos.concat([newTodo]));
todos.concat(newTodo)

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
> +      item.isEditing = item.id === todo.id ? true : false;
`item.id === todo.id ? true : false` can be shortened as `item.id === todo.id`

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos([...editList]);
Since `arr. map` has created a new array, there is no need to use `[...editList]` to clone the array again.

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
>      setTodos([...todos]);
Use arr.map

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
>      setTodos([...todos]);
Use arr.map

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos([...remainedTodos]);
`arr.filter` has created a new array, there is no need to use `[...remainedTodos]` to clone the array again.

2021-05-25 09:13 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    const newTodo = {
You should declare its type as `Todo`.

2021-05-27 06:56 UTC, laurenchen0631 requested changes

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/AddTodoForm.tsx
> +  }));
`makeStyles` should be defined out of the component.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/AddTodoForm.tsx
> +    <form className={classes.addTodoForm}>
You should only use component from Material-UI.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/AddTodoForm.tsx
> +// eslint-disable-next-line react/prop-types
You can turn off `react/prop-types` in eslintrc.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/App.tsx
> +      setTodos(() => newTodos);
Meaningless callback setState.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos(() => todos.concat(newTodo));
Wrong.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos(() => editList);
Wrong.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos(() => savedTodos);
Wrong.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos(() => cancelEditTodos);
Wrong.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/App.tsx
> +    setTodos(() => remainedTodos);
Wrong.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/TodoList.tsx
> +  }, [todos]);
Meaningless `useMemo`

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/TodoList.tsx
> +  }));
out of component.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/TodoListItem.tsx
> +    setEdit(() => e.target.value);
It doesn't need callback since it doesn't use the old value.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/TodoListItem.tsx
> +  }));
out of component.

2021-05-27 06:56 UTC, laurenchen0631 commented on src/Components/TodoListItem.tsx
> +        style={{ display: "inline-block" }}
Use classname.

2021-05-27 06:57 UTC, laurenchen0631 commented
Why do you still use branch `auto-format`?
Use git-flow and choose another name.

2021-05-27 10:11 UTC, merged

2021-05-28 06:25 UTC, ecstaciEva commented on src/Components/AddTodoForm.tsx
> +    <form className={classes.addTodoForm}>
I used FormControl but with 2 inputs inside it ( input and submit),
so I changed the element to <form> according to [the previous code-review](https://github.com/ecstaciEva/todo-list-typescript/pull/2#discussion_r637834338).

I changed it back to FormControl and remove the type="submit" from the Button this time,
but I'm not sure whether it is the right component I should be using.